
title: JosieOpt Optimization Blog
email: josielc1226@gmail.com
description: Sharing optimization models and Python code
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed

