title: VelOpt Optimization Blog
email: josielc1226@gmail.com
description: >-
  A clean blog to share optimization models and Python code.
baseurl: ""
url: "https://josiey.github.io"
markdown: kramdown
kramdown:
  input: GFM
# theme: minima
plugins:
  - jekyll-feed
