
title: Josie.Y's Blog
email: josielc1226@gmail.com
description: Sharing optimization models and Python code
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
theme: minima

# Add this to include your custom styles
sass:
  style: compressed

# Tell Jekyll to use your CSS
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      css: "/assets/CSS/custom.css"
plugins:
  - jekyll-feed

